name: "Lint and Tests"
on: 
  push: 
    branches: 
      - master 
  pull_request: 

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
  
    

    - name: Install dependencies
      run: |
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements.lint.txt ]; then pip install -r requirements.lint.txt; fi
        if [ -f requirements.test.txt ]; then pip install -r requirements.test.txt; fi
    - name: Lint with Black
      run: |
        make style-check
    - name: Style check with Flake8
      run: |
        make check-flake8
    - name: Run tests and coverage
      run: |
        make tests
